Feature/cdcinitializer 28
SAP/sap-customer-data-cloud-accelerator pull request #82
Opened 2024-01-03 12:13 UTC by Helsinky

2024-01-04 12:45 UTC, bmmsantos requested changes

2024-01-04 12:45 UTC, bmmsantos commented on README.md
> +On the cdc-accelerator.json file, there are two mandatory properties that the user has to fill, the "source" and "deploy".
Use the same syntax to refer to files, `cdc-accelerator.json` or other names, `source`, `deploy` (as it is in the previous paragraph)

2024-01-04 12:45 UTC, bmmsantos commented on README.md
> +    "features": [""]
This should be an empty array, []

2024-01-04 12:45 UTC, bmmsantos commented on README.md
> +If the user needs to add that filter to all the ApiKeys that are on the configuration file, he can simply replace the apikey ID to '\*' for example:
Remove the \ from '\*'
The filter with apiKey * is not for all api keys, is just for the other api keys that do not have already a specific filter configuration.
If there is not a filter applied to any api key then a filter for api key * is for all api keys

2024-01-04 12:45 UTC, bmmsantos commented on README.md
> +The operation can be replaced by Init, Reset, Build, Deploy.
The name of the operations should be lower case, Init, Reset, Build, Deploy are not accepted

2024-01-04 12:48 UTC, bmmsantos commented on README.md
> +### How to use filters on preview
This section needs a context, what is preview?
Where the filter is applied? (file src/index.html)

2024-01-08 17:15 UTC, bmmsantos commented on README.md
> +To get started it is necessary to have git, javascript and nodejs installed on the local machine.
javascript do not gets installed, it's available out of the box

2024-01-08 17:17 UTC, bmmsantos commented on README.md
> +On the cdc-accelerator.json file, there are two mandatory properties that the user has to fill, the "source" and "deploy".
Use the same syntax to refer to files, cdc-accelerator.json or other names, source, deploy (see line 45 where the names are between ``)

2024-01-08 17:23 UTC, bmmsantos commented on README.md
> +### Adding the filter to all the ApiKeys that do not have already a specific filter that are on the configuration file
What about the title to be "Adding a filter to all the Api keys that do not have already a specific filter"?

2024-01-10 17:02 UTC, luismarques-io approved these changes

2024-01-10 17:25 UTC, merged